name: Build .NET 9 Application

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

env:
    NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages


jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '9.0.x'

      - name: Setup Git Version
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
            versionSpec: '6.3.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
            useConfigFile: true

      - name: Version
        run: |
          echo Building ${{ steps.gitversion.outputs.SemVer }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --no-incremental /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --verbosity normal
